<a href="https://colab.research.google.com/github/saumya0303/Neural_Network_Creation/blob/master/Tensorflow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import numpy as np

In [4]:
print(tf.__version__)

2.2.0-rc2


In [0]:
np.random.seed(101)
tf.random.set_seed(101)

In [0]:
rand_a=np.random.uniform(0,100,(5,5))

In [13]:
print(rand_a)

[[52.06653967 57.87895355 73.48190583 54.19617722 91.31535577]
 [80.7920151  40.29978307 35.72243428 95.28767147 34.36315779]
 [86.50998163 83.02777122 53.81614492 92.24693726  9.71464798]
 [10.28474932 70.15072957 89.04798691 15.95603009 27.55725449]
 [67.24915297 16.4303124  70.13711366 48.76352222 68.06777682]]


In [0]:
rand_b=np.random.uniform(0,100,(5,1))

In [15]:
print(rand_b)

[[52.15481923]
 [ 4.33966944]
 [22.39366035]
 [57.52050869]
 [12.04336601]]


In [17]:
a=tf.placeholder(tf.float32)#no placeholder and session in tensorflow v.2

AttributeError: ignored

In [18]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [0]:
a=tf.placeholder(tf.float32)

In [0]:
b=tf.placeholder(tf.float32)

In [0]:
add_op=a+b

In [0]:
mul_op=a*b

In [26]:
with tf.Session() as sess:
  add_result=sess.run(add_op,feed_dict={a:10,b:20})
  print(add_result)
  mult_result=sess.run(mul_op,feed_dict={a:10,b:20})
  print(mult_result)

30.0
200.0


In [24]:
with tf.Session() as sess:
  add_result=sess.run(add_op,feed_dict={a:rand_a,b:rand_b})
  print(add_result)

[[104.22136  110.03377  125.63672  106.351    143.47017 ]
 [ 85.13168   44.63945   40.062103  99.62734   38.702827]
 [108.90364  105.42143   76.2098   114.6406    32.108307]
 [ 67.80526  127.671234 146.5685    73.47654   85.07776 ]
 [ 79.29252   28.473679  82.18048   60.80689   80.111145]]
